"""
AynovaX - Reporting Engine
--------------------------
Generates professional PDF documents for executive summaries.
Transforms raw database logs into actionable business intelligence documents.
"""

from fpdf import FPDF
from datetime import datetime
import os

class ExecutiveReport(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 15)
        self.cell(80)
        self.cell(30, 10, 'AynovaX Enterprise Report', 0, 0, 'C')
        self.ln(20)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}/{{nb}} - Generated by AynovaX AI Core', 0, 0, 'C')

def generate_pdf_report(logs, filename="report.pdf"):
    pdf = ExecutiveReport()
    pdf.alias_nb_pages()
    pdf.add_page()
    
    # --- TITLE SECTION ---
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, f'Shift Summary: {datetime.now().strftime("%Y-%m-%d %H:%M")}', 0, 1)
    pdf.set_font('Arial', '', 10)
    pdf.cell(0, 10, 'Predictive Maintenance & Financial Audit', 0, 1)
    pdf.ln(10)

    # --- KPI SUMMARY (Business Logic) ---
    total_scans = len(logs)
    defects = len([l for l in logs if "Defective" in l.prediction or "Critical" in l.prediction])
    net_profit = sum([l.financial_impact for l in logs])
    
    pdf.set_fill_color(240, 240, 240)
    pdf.set_font('Arial', 'B', 10)
    pdf.cell(0, 10, '1. EXECUTIVE METRICS', 0, 1, 'L', 1)
    pdf.ln(5)
    
    pdf.set_font('Arial', '', 10)
    pdf.cell(50, 10, f'Total Operations: {total_scans}', 0, 0)
    pdf.cell(50, 10, f'Defect Rate: {((defects/total_scans)*100 if total_scans else 0):.1f}%', 0, 0)
    
    # Financial Conditional Formatting
    profit_text = f"${net_profit:.2f} USD"
    pdf.set_text_color(192, 0, 0) if net_profit < 0 else pdf.set_text_color(0, 128, 0)
    pdf.cell(50, 10, f'Net Financial Impact: {profit_text}', 0, 1)
    pdf.set_text_color(0, 0, 0) 
    pdf.ln(10)

    # --- INCIDENT TABLE ---
    pdf.set_fill_color(240, 240, 240)
    pdf.set_font('Arial', 'B', 10)
    pdf.cell(0, 10, '2. CRITICAL INCIDENT LOG (Last 20)', 0, 1, 'L', 1)
    pdf.ln(5)

    # Table Header
    pdf.set_font('Arial', 'B', 9)
    pdf.cell(30, 8, 'Time', 1)
    pdf.cell(40, 8, 'Status', 1)
    pdf.cell(30, 8, 'Impact', 1)
    pdf.cell(40, 8, 'Ticket ID', 1)
    pdf.ln()

    # Table Rows
    pdf.set_font('Arial', '', 8)
    for log in logs[:20]: 
        # Time formatting
        time_str = log.timestamp.strftime("%H:%M:%S")
        # Truncate status if too long
        status_clean = log.prediction.split('(')[0][:20]
        
        pdf.cell(30, 8, time_str, 1)
        pdf.cell(40, 8, status_clean, 1)
        pdf.cell(30, 8, f"${log.financial_impact}", 1)
        pdf.cell(40, 8, log.maintenance_ticket or "N/A", 1)
        pdf.ln()

    # --- AI RECOMMENDATION SUMMARY ---
    pdf.ln(10)
    pdf.set_fill_color(240, 240, 240)
    pdf.set_font('Arial', 'B', 10)
    pdf.cell(0, 10, '3. AI SYSTEM NOTES', 0, 1, 'L', 1)
    pdf.set_font('Arial', 'I', 9)
    pdf.multi_cell(0, 10, "This report was automatically generated by the AynovaX Random Forest Engine. Financial estimates are based on standard production material costs. Please archive this document for ISO-9001 compliance.")

    # Output
    # Create 'reports' folder if not exists
    if not os.path.exists("reports"):
        os.makedirs("reports")
        
    file_path = f"reports/{filename}"
    pdf.output(file_path)
    return file_path